apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/alexandresb/edge-service/k8s?ref=e327036e18f9eaee289d3f57ca616823ad640e04

patches:
  - path: patch_env.yaml
  - path: patch_volumes.yaml
  - path: patch_resources.yaml
  - path: patch_ingress.yaml

configMapGenerator:
  - behavior: merge
    files:
      - application-prod.yaml
    name: edge-config

images:
  - name: edge-service # le nom de l'image indiqué dans le manifeste de base catalog_deployment.yaml
    newName: ghcr.io/alexandresb/edge-service
    newTag:  e327036e18f9eaee289d3f57ca616823ad640e04 #hash de la dernière release

replicas:
  - count: 1
    name: edge-service