apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: #les manifestes dans le repo catalog-service servent de base à la customisation de catalog-service
  - https://github.com/alexandresb/edge-service/k8s?ref=main

patches:
  - path: patch_env.yaml

configMapGenerator:
  - behavior: merge
    files:
      - application-staging.yaml
    name: edge-config

#redéfinition de l'image utilisée dans un environnement de déploiement Staging
images:
  - name: edge-service # le nom de l'image indiqué dans le manifeste de déploiement de base
    newName: ghcr.io/alexandresb/edge-service
    newTag: latest

#déploiement de 2 pods dans un env staging
replicas:
  - count: 1
    name: edge-service