apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: #les manifestes dans le repo catalog-service servent de base à la customisation de catalog-service
  - https://github.com/alexandresb/catalog-service/k8s?ref=v2

patches:
  - path: patch_env.yaml

configMapGenerator:
  - behavior: merge
    files:
      - application-staging.yaml
    name: catalog-config
#redéfinition de l'image utilisée dans un environnement de déploiement Staging

images:
  - name: catalog-service # le nom de l'image indiqué dans le manifeste de base catalog_deployment.yaml
    newName: ghcr.io/alexandresb/catalog-service
    newTag: latest

#déploiement de 2 pods dans un env staging
replicas:
  - count: 2
    name: catalog-service