apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/alexandresb/order-service/k8s?ref=52ff6432a7eb0111062b4cb7a7fb0e442de8788a

patches:
- path: patch_env.yaml
- path: patch_volumes.yaml
- path: patch_resources.yaml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yaml
  name: order-config

images:
- name: order-service
  newName: ghcr.io/alexandresb/order-service
  newTag: 52ff6432a7eb0111062b4cb7a7fb0e442de8788a

replicas:
- count: 1
  name: order-service
