apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/alexandresb/order-service/k8s?ref=7561c78c31a54d8b4bf28f5172c19e0c91695689

patches:
  - path: patch_env.yaml
  - path: patch_volumes.yaml
  - path: patch_resources.yaml

configMapGenerator:
  - behavior: merge
    files:
      - application-prod.yaml
    name: order-config

images:
  - name: order-service # le nom de l'image indiqué dans le manifeste de base catalog_deployment.yaml
    newName: ghcr.io/alexandresb/order-service
    newTag: 7561c78c31a54d8b4bf28f5172c19e0c91695689 #hash de la dernière release

replicas:
  - count: 1
    name: order-service