apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/alexandresb/catalog-service/k8s?ref=666f2b5a065bc7f4903d65f3b5db7ee195bc0f8f

patches:
  - path: patch_env.yaml
  - path: patch_volumes.yaml
  - path: patch_resources.yaml

configMapGenerator:
  - behavior: merge
    files:
      - application-prod.yaml
    name: catalog-config

images:
  - name: catalog-service # le nom de l'image indiqué dans le manifeste de base catalog_deployment.yaml
    newName: ghcr.io/alexandresb/catalog-service
    newTag: 666f2b5a065bc7f4903d65f3b5db7ee195bc0f8f #hash de la dernière release

replicas:
  - count: 2
    name: catalog-service